name: velocity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pylint=2.17.5
  - jupyter=1.0.0
  - matplotlib=3.7.2
  - numpy=1.24.4
  - pandas=1.5.3
  - pip:
      - seaborn==0.12.2